name: K3s Cluster Provisioning

on:
  workflow_dispatch:
    inputs:
      worker_count:
        description: "Number of worker nodes"
        required: true
        default: "1"

jobs:
  provision:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Ensure PATH includes Homebrew
        run: echo "PATH=$PATH:/opt/homebrew/bin" >> $GITHUB_ENV

      - name: Cleanup existing Multipass VMs
        run: |
          echo "Deleting old k3s-master and worker nodes if they exist..."
          # Delete master if exists
          if multipass list | grep -q "k3s-master"; then
            multipass delete k3s-master
            multipass purge
          fi
          # Delete all workers that exist
          multipass list | grep "k3s-worker-" | awk '{print $1}' | while read vm; do
            echo "Deleting $vm"
            multipass delete "$vm"
            multipass purge
          done || echo "No worker nodes to delete"

      - name: Run Ansible Playbook
        run: ansible-playbook -i inventory.yml dynamic_k3s_provisioning.yaml -e "worker_count=${{ github.event.inputs.worker_count }}"
        env:
          PATH: /opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:$PATH
